- name: Add hosts
  hosts: prometheus
  become: true
  gather_facts: false
  vars:
    - HOSTS_FILE: /etc/hosts
  tasks:
    - name: 'Add hosts to {{ HOSTS_FILE }}'
      lineinfile:
        dest: '{{ HOSTS_FILE }}'
        line: '{{ item }}'
        backup: yes
      with_items:
        - 10.30.40.9    elasticsearch-node-1
        - 10.30.40.10   elasticsearch-node-2
        - 10.30.40.11   elasticsearch-node-3
        - 10.30.60.4    hhg-database-3
        - 10.30.60.6    hhg-mb-database
        - 10.30.60.5    hhg-redis-3
        - 10.30.60.8    postgresql-staging
        - 10.30.60.9    postgresql-production
        - 10.30.60.10   sentry-redis-master-0
        - 10.30.60.11   sentry-postgresql
        - 10.30.60.13   hhg-database-dev
        - 10.30.60.14   hhg-database-staging-hotfix
        - 10.30.60.15   hhg-database-hellosehat
        - 10.30.20.3    hhg-vpn
        - 10.30.40.16   kafka-1
        - 10.30.40.17   kafka-2
        - 10.30.40.18   kafka-3
        - 10.30.40.20   sentry-kafka-1
        - 10.30.40.21   sentry-kafka-2
        - 10.30.40.22   sentry-kafka-3
        - 10.30.40.24   sentry-rabbitmq-1
        - 10.30.40.12   logstash-1
        - 10.30.40.5    metabase
        - 10.30.40.15   zookeeper-1
        - 10.30.40.23   sentry-zookeeper-1
        - 10.30.40.30   sonarqube-prod-001
        - 10.30.40.40   reportportal
        - 10.148.0.62   hhg-mongo-staging
        - 10.30.50.13   mongodb-config-0-001
        - 10.30.50.14   mongodb-config-1-001
        - 10.30.50.15   mongodb-config-2-001
        - 10.30.50.10   mongodb-sharding1-0-001
        - 10.30.50.11   mongodb-sharding1-1-001
        - 10.30.50.12   mongodb-sharding1-2-001
        - 10.30.50.16   mongos-0-001
        - 10.30.50.50   sidis-postgresql
        - 10.30.42.10   gitlab-server
        - 10.30.43.5    selfmanaged-runner-manager
        - 10.148.0.25   sidis-dev-1
        - 10.148.0.9    rancher
        - 10.148.0.6    elasticsearch-0
        - 10.30.50.16   mongos-0-001
        - 10.148.0.21   cloudflare_exporter