- name: Add hosts
  hosts: prometheus
  become: true
  gather_facts: false
  vars:
    - HOSTS_FILE: /etc/hosts
  tasks:
    - name: 'Add hosts to {{ HOSTS_FILE }}'
      lineinfile:
        dest: '{{ HOSTS_FILE }}'
        line: '{{ item }}'
        backup: yes
      with_items:
        - 10.30.40.9    elasticsearch-node-1