- name: Add hosts
  hosts: prometheus
  become: true
  gather_facts: false
  vars:
    - HOSTS_FILE: /etc/hosts
  tasks:
    - name: 'Add hosts to {{ HOSTS_FILE }}'
      lineinfile:
        dest: '{{ HOSTS_FILE }}'
        line: '{{ item }}'
        backup: yes
      with_items:
        - 159.223.83.104    centos-s-1vcpu-1gb-sgp1-03
        - 91.228.115.115    DEDI-150139
        - 51.15.6.127       AMS-411137