# - import_playbook: ../ssh-hostkey-checking.yaml

- name: Install Mysql Exporter
  hosts: mysql
  become: yes
  gather_facts: false
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
  tasks:
    - name: Add the user "mysql_exporter"
      ansible.builtin.user:
        name: mysql_exporter
        shell: /bin/false
        system: true
    - name: mkdir /opt
      file:
        path: /opt
        state: directory
    - name: Extract source
      ansible.builtin.unarchive:
        src: ./source/mysqld_exporter-0.13.0.linux-amd64.tar.gz
        dest: /opt
        owner: mysql_exporter
    - name: Install unit file to systemd
      copy:
        src: ./conf/mysql_exporter.service
        dest: /etc/systemd/system/mysql_exporter.service
        owner: root
        group: root
        mode: 0600
    - name: Configure systemd to use service and start
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: mysql_exporter.service