- name: Reload Configuration
  hosts: prometheus
  become: true
  gather_facts: false
  vars:
    - ROOT_DIR: /root/ezbi_monitoring
    - CONF_DIR: /root/ezbi_monitoring/conf
  tasks:
    - name: Copy alertmanager.yml
      copy:
        src: conf/alertmanager.yml
        dest: '{{ CONF_DIR }}/alertmanager.yml'
    - name: Copy message.tmpl
      copy:
        src: conf/message.tmpl
        dest: '{{ CONF_DIR }}/message.tmpl'
    - name: Copy docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: '{{ ROOT_DIR }}/docker-compose.yml'
    - name: Reload config
      shell:
        # cmd: docker kill --signal=SIGHUP prometheus
        cmd: 'docker-compose -f {{ ROOT_DIR }}/docker-compose.yml restart alertmanager'
    - name: Check running container
      shell:
        cmd: 'docker ps && sleep 10'
      register: container_checker

    - debug: var=container_checker.stdout_lines