global:
  resolve_timeout: 5m
route:
  group_by: ['instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

  # Default receiver.
  receiver: "gmail"

  routes:
  - match:
      alertname: Watchdog
    receiver: "null"
  - match:
      alertname: CPUThrottlingHigh
    receiver: "null"

receivers:
- name: "null"
- name: "gmail"
  email_configs:
    - send_resolved: true
      to: "duyquangou1989@gmail.com,umarbits@gmail.com"
      from: "umar.systemalert@gmail.com"
      smarthost: smtp.gmail.com:587
      auth_username: "umar.systemalert@gmail.com"
      auth_identity: "umar.systemalert@gmail.com"
      auth_password: ""


# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match_re:
#       severity: 'warning|info'
#     equal: ['alertname']