global:
  resolve_timeout: 5m
route:
  group_by: ['alertname','instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

  # Default receiver.
  receiver: "gmail"

  routes:
  # continue defaults to false, so the first match will end routing.
  - match:
      alertname: Watchdog
    receiver: "null"
  - match:
      alertname: CPUThrottlingHigh
    receiver: "null"

receivers:
- name: "null"
# - name: google_chat
#   webhook_configs:
#   - url: http://calert:6000/dispatch
- name: gmail
  email_configs:
    - send_resolved: true
      to: "duyquangou1989@gmail.com"
      from: "hhg.system@hellohealthgroup.com"
      smarthost: smtp.gmail.com:587
      auth_username: "umar.ezbi@gmail.com"
      auth_identity: "umar.ezbi@gmail.com"
      auth_password: "pbfmbxgpwafpvdpa"

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match_re:
      severity: 'warning|info'
    equal: ['alertname','namespace','instance']